/**
 * Pull the two webfonts into the repo so no page has to ask Google for them.
 *
 * Why bother: the verifier is the page a sceptic opens to check a receipt without
 * trusting us. A third-party font request on it means every person who verifies anything
 * tells Google they did, and the page stops working offline or behind a strict firewall —
 * neither of which is acceptable on the one artifact whose whole claim is independence.
 *
 * Both faces are SIL Open Font License 1.1, which permits redistribution provided the
 * licence travels with them. It is written out beside the files.
 *
 * Run when a font needs changing, not on every build — the output is committed:
 *   node scripts/vendor-fonts.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SPEC =
  "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1" +
  "&family=IBM+Plex+Mono:wght@400;500;600" +
  // The grotesk the demo UI is set in. Self-hosted rather than left to a system stack,
  // because "whatever sans this machine has" is Segoe UI on Windows and SF on a Mac, and
  // a display face at 80px shows that difference immediately.
  "&family=Inter:wght@400;500;600&display=swap";

// A browser UA, or the service returns truetype rather than woff2 — four times the bytes
// for no benefit to any browser made this decade.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/**
 * Latin only. The other subsets are ~70% of the payload and neither page contains a
 * single Cyrillic, Greek or Vietnamese character; `latin-ext` stays because the demo
 * data does contain accented names.
 */
const WANTED = new Set(["latin", "latin-ext"]);

const TARGETS = ["apps/verify-page/public/fonts", "apps/web/public/fonts"];

const css = await fetch(SPEC, { headers: { "user-agent": UA } }).then((r) => r.text());

/** Split the stylesheet into blocks, each preceded by a `/* subset *\/` comment. */
function parseFaces(sheet) {
  const out = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(sheet))) {
    const [, subset, body] = m;
    const pick = (k) => body.match(new RegExp(`${k}:\s*([^;]+);`))?.[1]?.trim();
    const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    out.push({
      subset,
      family: (pick("font-family") ?? "").replace(/['"]/g, ""),
      style: pick("font-style") ?? "normal",
      weight: pick("font-weight") ?? "400",
      unicodeRange: pick("unicode-range") ?? "",
      url,
    });
  }
  return out;
}

const faces = parseFaces(css).filter((f) => WANTED.has(f.subset));
if (faces.length === 0) throw new Error("parsed no font faces — the stylesheet format changed");

const rules = [];
let total = 0;

for (const f of faces) {
  const slug = f.family.toLowerCase().replace(/\s+/g, "-");
  const name = `${slug}-${f.weight}-${f.style}-${f.subset}.woff2`;

  const bytes = new Uint8Array(await fetch(f.url, { headers: { "user-agent": UA } }).then((r) => r.arrayBuffer()));
  // woff2 files begin with the signature `wOF2`. Anything else means we saved an error
  // page under a font's name, which fails silently later as a face that never loads.
  const sig = String.fromCharCode(...bytes.slice(0, 4));
  if (sig !== "wOF2") throw new Error(`${name} is not woff2 (got ${JSON.stringify(sig)})`);

  for (const dir of TARGETS) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, name), bytes);
  }
  total += bytes.length;
  console.log(`  ${name.padEnd(44)} ${(bytes.length / 1024).toFixed(1)} KB`);

  rules.push(
    `@font-face {\n` +
      `  font-family: '${f.family}';\n` +
      `  font-style: ${f.style};\n` +
      `  font-weight: ${f.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('./fonts/${name}') format('woff2');\n` +
      (f.unicodeRange ? `  unicode-range: ${f.unicodeRange};\n` : "") +
      `}`,
  );
}

const header = `/* Self-hosted so no page here depends on a third party to render.
 * Generated by scripts/vendor-fonts.mjs — edit that, not this.
 * IBM Plex Mono and Instrument Serif are SIL Open Font License 1.1; see fonts/OFL.txt. */`;

for (const dir of TARGETS) {
  writeFileSync(join(dir, "..", "fonts.css"), `${header}\n\n${rules.join("\n\n")}\n`);
}

console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(1)} KB total, into ${TARGETS.length} places`);
